
import React from 'react';
import { LectureSummary } from '../types';

interface InfographicProps {
  summary: LectureSummary;
}

const Infographic: React.FC<InfographicProps> = ({ summary }) => {
  return (
    <div id="infographic-export" className="infographic-container font-sans flex flex-col gap-8 shadow-2xl mx-auto">
      <header className="border-b border-white/20 pb-6">
        <div className="text-indigo-400 font-bold tracking-widest text-xs mb-2 uppercase">Lecture Intelligence</div>
        <h1 className="text-3xl font-black leading-tight mb-4">{summary.topic}</h1>
        <div className="flex flex-wrap gap-2">
          {summary.keywords.slice(0, 3).map((kw, i) => (
            <span key={i} className="text-[10px] bg-indigo-600 px-2 py-1 rounded">#{kw}</span>
          ))}
        </div>
      </header>

      <section>
        <h2 className="text-indigo-400 font-bold text-sm mb-4 flex items-center gap-2">
          <span className="w-1 h-4 bg-indigo-400 inline-block"></span>
          KEY INSIGHTS
        </h2>
        <div className="grid gap-3">
          {summary.insights.slice(0, 2).map((ins, i) => (
            <div key={i} className="bg-white/5 p-4 rounded-lg border border-white/10">
              <div className="text-indigo-300 font-bold text-[10px] mb-1">{ins.category}</div>
              <p className="text-sm text-slate-200">{ins.content}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="flex-grow">
        <h2 className="text-indigo-400 font-bold text-sm mb-4 flex items-center gap-2">
          <span className="w-1 h-4 bg-indigo-400 inline-block"></span>
          CORE TAKEAWAYS
        </h2>
        <div className="space-y-6">
          {summary.mainPoints.slice(0, 3).map((pt, i) => (
            <div key={i} className="relative pl-6 border-l border-indigo-500/30">
              <div className="absolute -left-[5px] top-1 w-2 h-2 rounded-full bg-indigo-500"></div>
              <h3 className="font-bold text-sm text-white mb-2">{pt.title}</h3>
              <p className="text-xs text-slate-400 leading-relaxed">{pt.details[0]}</p>
            </div>
          ))}
        </div>
      </section>

      <footer className="mt-auto pt-6 border-t border-white/10 flex justify-between items-end">
        <div>
          <div className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">Generated by</div>
          <div className="text-lg font-black text-indigo-400">Lecture Lens</div>
        </div>
        <div className="text-[10px] text-slate-600 italic">
          AI Summarization Report
        </div>
      </footer>
    </div>
  );
};

export default Infographic;
